### PR TITLE
[API break] tc: Reorganize the code base

### PR DESCRIPTION
**Pull request by cathay4t**
* This patch is first preparation on stable release 1.0 for submodule tc. The detailed checklist for developer is stated in README.md file.
 * Stored constants into where it been used. Will remove `constants.rs` once all components finished.
 * Replace `pub use self::*` to explicit expose.
 * Renamed many struct/enum to hold `Tc` prefix.
 * Complete rewrite of `TcXstats` as its is wrong according to kernel code.

### CODE REVIEW

**Comment by cathay4t** [comment]
@mmynk Can you take a look on the code layout?

The code is compiling OK, but I need to study TC to expand the test cases.

**Comment by mmynk** [comment]
> @mmynk Can you take a look on the code layout?

@cathay4t Sure will take a deeper look this week.
I glanced through the code once and it looked okay to me. Just wanted to call out, I don't think we should add specific qdisc parsing in this library. For example, parsing for [FQ_CODEL](https://github.com/rust-netlink/netlink-packet-route/pull/63/files#diff-a21a7fade82dee3e29b097cf1ccd351a1b4bb4eb5a51765f165228a256e67c33). This can reside in the `rust-tc` library where I plan to add parsing for other [qdiscs](https://man7.org/linux/man-pages/man8/tc.8.html#CLASSLESS_QDISCS) and [classes](https://man7.org/linux/man-pages/man8/tc.8.html#CLASSFUL_QDISCS) as well and it is also tightly coupled with [netlink-packet-route](https://github.com/rust-netlink/netlink-packet-route) and other [rust-netlink](https://github.com/rust-netlink) libraries.

So I believe it might be better to keep [`Options`](https://github.com/rust-netlink/netlink-packet-route/pull/63/files#diff-0a727500ee22446555b7cf8296cb33e8affb6962507140dc1d7095a4d730dce6R36) as raw bytes in this library to reflect low level netlink packets more closely.

**Comment by cathay4t** [comment]
> > @mmynk Can you take a look on the code layout?
> 
> @cathay4t Sure will take a deeper look this week. I glanced through the code once and it looked okay to me. Just wanted to call out, I don't think we should add specific qdisc parsing in this library. For example, parsing for [FQ_CODEL](https://github.com/rust-netlink/netlink-packet-route/pull/63/files#diff-a21a7fade82dee3e29b097cf1ccd351a1b4bb4eb5a51765f165228a256e67c33). This can reside in the [netlink-tc](https://github.com/mmynk/rust-tc) library where I plan to add parsing for other [qdiscs](https://man7.org/linux/man-pages/man8/tc.8.html#CLASSLESS_QDISCS) and [classes](https://man7.org/linux/man-pages/man8/tc.8.html#CLASSFUL_QDISCS) as well and it is also tightly coupled with [netlink-packet-route](https://github.com/rust-netlink/netlink-packet-route) and other [rust-netlink](https://github.com/rust-netlink) libraries.
> 
> So I believe it might be better to keep [`Options`](https://github.com/rust-netlink/netlink-packet-route/pull/63/files#diff-0a727500ee22446555b7cf8296cb33e8affb6962507140dc1d7095a4d730dce6R36) as raw bytes in this library to reflect low level netlink packets more closely.

My design of rust-netlink is:
 * `netlink-packet-xxx` parse netlink message and avoiding exposing Vec<u8>. This layer can be omit when the netlink parsing is too simple, for example `mptcp-pm` crate contains both API and netlink parsing.
 * `netlink-tc`, `rtnetlink`, `ethtool`, `mptcp-pm`, `wl-nl80211` provide fancy user facing API which handle communication to/from kernel netlink socket.

For example,  the `filter/class` u32 has `mask`, `val`, `off`, `offmask` which should be parsed in `netlink-packet-route`. The `netlink-tc` should be filling these data with correct value and send to kernel for API serving:
`tc filter add dev dummy1 parent ffff: matchall action mirred egress mirror dev dummy2`.

**Comment by cathay4t** [comment]
The third layer would be `rust-iproute2`  workshop with `tc` as sub-crate.

**Comment by cathay4t** [comment]
The patch is ready for review! The unit test cases has covered all filter/action/option/stats/qdisc codes.

**Comment by mmynk** [comment]
Agree with your points.

But I believe parsing for specific classful and classless qdiscs should be left to `netlink-tc`.
It doesn't make sense just to add parsing for a single qdisc - `fq_codel` and leave [others](https://man7.org/linux/man-pages/man8/tc.8.html), eg: htb, sfq, etc.

I also couldn't understand what some of the objects like `TcAction` and `TcActionAttribute` are trying to parse from kernel. A one line comment for the corresponding kernel definitions (like `// defined in include/uapi/linux/rtnetlink.h as TCA_ACTION` or something similar) would be helpful.

**Comment by cathay4t** [comment]
> Agree with your points.
> 
> But I believe parsing for specific classful and classless qdiscs should be left to `netlink-tc`. It doesn't make sense just to add parsing for a single qdisc - `fq_codel` and leave [others](https://man7.org/linux/man-pages/man8/tc.8.html), eg: htb, sfq, etc.

We can expand more qdisc/filter/class/actions later. I don't like exposing `Vec<u8>` in `netlink-packet-route` crate, this is lower level netlink parsing create, `netlink-tc` is responsible for socket communication and API wrapping. They serve different purpose.

> 
> I also couldn't understand what some of the objects like `TcAction` and `TcActionAttribute` are trying to parse from kernel. A one line comment for the corresponding kernel definitions (like `// defined in include/uapi/linux/rtnetlink.h as TCA_ACTION` or something similar) would be helpful.

The goal of `rust-netlink` is saving people from reading kernel code.

**Comment by cathay4t** [comment]
There is no `TCA_ACTION`. Each filter has their own NLA type, for example `u32` has `TCA_U32_ACT`. I think the rust code is enough to explain how this action is parsed.

**Comment by cathay4t** [comment]
I assume you mean 19f14357d15f5d38ff47cc9bef9d28bdb7469420 (tc: Fix DecodeError on sfq scheduler) , unfortunately, the API is changed after 0.17.1 before that patch is merged, I cannot do minor release with that patch only.

If you want to ship your project, you may consider do `cargo vendor` and apply the patch afterwards.

**Comment by cathay4t** [comment]
The reason the tc parsing should be here is because other component of crate is parsing the netlink message. If we expose `Vec<u8>` in this crate for `tc`, we are do partial parsing which bad for user experience.  Considering previous state of tc codes there, I would like to review the parsing code carefully.

**Comment by cathay4t** [comment]
If not other objection, I would like to move on, other PR is waiting. Considering all unit test cases are captured via nlmon, I think the patch is good enough to merge.

**Review by mmynk — APPROVED** [review]
looked at the qdisc parsing code, looks good to me

**Pull request merged**
