### PR TITLE
link: ipvlan: Change mode type from u16 to Enum.

### PR DESCRIPTION
**Pull request by xujunjie-cover**
link: ipvlan: Change mode type from u16 to Enum.

### CODE REVIEW

**Review by cathay4t — APPROVED** [review]
LGTM.

**Comment by cathay4t** [comment]
@xujunjie-cover Thanks for the contribution! Please run `cargo fmt` against your patch to make CI happy. After that, we can merge it.

**Comment by xujunjie-cover** [comment]
> @xujunjie-cover Thanks for the contribution! Please run `cargo fmt` against your patch to make CI happy. After that, we can merge it.

done. Thanks.

**Comment by cathay4t** [comment]
Hi @xujunjie-cover, please wait 1 more week for other PR to merged. When I will tag new release for you to use this in rtnetlink.

**Comment by xujunjie-cover** [comment]
> Hi @xujunjie-cover, please wait 1 more week for other PR to merged. When I will tag new release for you to use this in rtnetlink.

OK，I also want to add ipvtap, is that okay？

**Pull request merged**
