### PR TITLE
[API break] link: Reorganize the code base

### PR DESCRIPTION
**Pull request by cathay4t**
* This patch is first preparation on stable release 1.0 for submodule
   link. The detailed checklist for developer is stated in
   README.md file.

 * Stored constants into where it been used. Will remove `constants.rs`
   once all components finished.

 * Replace `pub use self::*` to explicit expose.

 * Removed `data` folder, `README.md` file has expanded to hold steps to
   capture netlink packets.

 * Removed `Unspec` as kernel not use it.

 * Removed `benches` folder as never used.

 * Removed dependency on `lazy_static`.

 * Added dependency on `log`. Considering `rtnetlink` also has it, no
   burden added to end user.

 * Many member of `InfoVxlan` changed from u8 to bool after confirmed
   with kernel code.

 * Changed API:
    * Rename:
      * `link::Nla` to `link::LinkAttribute` because `Nla` is a trait
      * `link:Info` to `link::LinkInfo`
      * `link::VethInfo` to `link::InfoVeth`
      * `link::InfoXfrmTun` to `link::InfoXfrm`
   * The AfSpec for ipv4 and ipv6 is rework. Please check `AfSpecUnspec`
   * Removed `link::Nla::AltIfName`. Use
     `link::LinkAttribute::PropList<vec![link::Prop::AltIfName]>`
     instead.
   * Changed `InfoVlan::Protocol<u16>` to
     `InfoVlan::Protocol<VlanProtocol>`.
    * `LinkHeader` changed to use enum instead raw integer on flags,
       address family and link layer type.
    * Change `LinkMessage.nlas` to `LinkMessage.attributes`.

 * Added:
    * `link::LinkFlag` and `LinkFlags` for `IFF_UP` and etc
    * `link::LinkLayerType` for `ARPHRD_ETHER` and etc
    * `crate::AddressFamily` for `AF_UNSPEC` and etc

### CODE REVIEW

**Comment by cathay4t** [comment]
@little-dude @JohnTitor Please take a look when you have time. I am planning to do 1.0 release before end of 2024. I am still adding more test cases to make sure this fundamental network crate is trustable.

**Review by JohnTitor — APPROVED** [review]
Didn't check the diff exhaustively (it's huge!) but the summary on OP sounds good to me.

**Comment by cathay4t** [comment]
Code 99% finished.

TODO:
 * Need to merge https://github.com/rust-netlink/netlink-packet-route/pull/58 into this one.
 * New PR to review properties one by one, especially flags should be enum or Vec<enum> instead raw integer. And avoid `Vec<u8>` unless that's how kernel defines.

**Comment by cathay4t** [comment]
Patch is ready for review.

I will create new PRs for follow up works:
 * Avoid using `Vec<u8>` unless kernel state so.
 * Convert integer flag to `enum`.
 * Convert bit-map flags to `Vec<enum>`.
 * More tests.
 * Do the same for `address`, `tc` and other subsystems.

**Comment by ydirson** [comment]
> Didn't check the diff exhaustively (it's huge!)

Indeed, not having individual reworks separated does not help to investigate alternative changes.

**Comment by cathay4t** [comment]
> I'm not convinced it is a good idea to remove the dependency on libc and duplicate here the job of maintaining mappings for address families and other things. Portability-wise, where the current implementation makes the compiler point to places where work is needed, this proposal just pretends the Linux constants are the truth, bypassing the value checks done by the libc crate's tests. This would effectively make this crate Linux-only.

Regarding this libc dependency, I actually got email requesting support on FreeBSD which suggest me to remove the dependency on libc as FreeBSD does not have libc constants we depend on,

These netlink crates are mainly developed and tested on Linux, and I don't have resource to test or maintain it on other platforms. In stead of future use case, so if you have proof that Unix and Linux holding different integer on constants used by this crate, please state them, we can discuss in new thread on whether bring libc dependency back or use conditional compiling.

Regarding the large patch, I have tried my best to refrain myself on changing more codes. Sorry. Mostly the code changes is just moving code around.

**Comment by cathay4t** [comment]
@ydirson Oh, just realize it is you who requested FreeBSD support. Could state which constants has conflicts between Unix and Linux and protected by libc?

**Comment by cathay4t** [comment]
Thanks for the suggestions. It seems the way we are handling `AddressFamily` need some work. Let me amend that.

**Comment by cathay4t** [comment]
@ydirson New patch uploaded for the cross-platform supports:

 * Use conditional compiling for FreeBSD in `address_family_freebsd.rs`.
 * Use conditional compiling for Linux and Fuchsia in `address_family_linux.rs`.
 * Other platform are using `address_family_fallback.rs` which hold minim libc supported AF_XXX constants.
 * CI has expanded to test the build on these rust targets:
   * `x86_64-unknown-linux-gnu`
   * `x86_64-unknown-freebsd`
   * `x86_64-unknown-fuchsia`
   * `x86_64-apple-darwin`
   * `x86_64-linux-android`

**Comment by ydirson** [comment]
@cathay4t that looks great!

Eager to see libc 0.3 debut so this can be applied to the netlink constants too!

I guess that to be able to try that on `xen-guest-agent` the next step would be propagating the API change to `rtnetlink`?

**Comment by cathay4t** [comment]
I have waited long enough for reviews. Let's move on and fix issue in new PR.

**Pull request merged**
