### PR TITLE
support IFLA_VRF_PORT_TABLE attribute

### PR DESCRIPTION
**Pull request by little-dude**
Links that belong to a VRF carry the VRF table ID in the link info. For a VRF link we already had these attributes:

```
LinkInfo([Kind(Vrf), Data(Vrf([TableId(10)]))])
```

For ports attached to a VRF we now have:

```
LinkInfo([Kind(Veth), PortKind(Vrf), PortData(VrfPort([TableId(10)]))])
```

This tells us that this veth interface belong to the VRF with table ID 10.

----

To test this:

```
sudo ip link add vrf-blue type vrf table 10                                                            
sudo ip link set dev vrf-blue up                                                                         
sudo ip link add veth20 type veth
sudo ip link set veth20 master vrf-blue # this link should now have the new attribute
```

Ref: https://github.com/torvalds/linux/blob/f2e367d6ad3bdc527c2b14e759c2f010d6b2b7a1/drivers/net/vrf.c#L1797

### CODE REVIEW

**Comment by little-dude** [comment]
The clippy failure is due to `TryFrom` which we explicitly import but that is part of the prelude in the 2021 edition. Should I fix this @cathay4t ?

**Comment by little-dude** [comment]
@cathay4t would you mind reviewing this?

**Review by cathay4t — CHANGES_REQUESTED** [review]
The code looks good to me. But I would like to see a unit test case parsing and emitting Vec<u8> captured on real VRF port. I have document on how to capture netlink message in https://github.com/rust-netlink/netlink-packet-route/blob/main/README.md

**Comment by little-dude** [comment]
@cathay4t  I added a test. Note that we might have a couple problemactic attributes when emitting packets, but that doesn't seem to be related to my changes, and I really don't have time to investigate further at the moment unfortunately. See the commented out part of the test.

**Review by cathay4t — APPROVED** [review]

**Comment by cathay4t** [comment]
https://github.com/rust-netlink/netlink-packet-route/issues/119 created for the FIXME.

**Pull request merged**
