### PR TITLE
add rich representation for VLAN QOS mapping

### PR DESCRIPTION
**Pull request by jreppnow**
Hi! 

Thanks for the cool crates. This PR adds a rich representation for VLAN QOS mappings. 
This is mainly used to allow user space applications to use the SOL_PRIORITY flag to set VLAN priority for their sockets. 

I used the implementation here as a reference: https://github.com/shemminger/iproute2/blob/main/ip/iplink_vlan.c

Notes:
- I used the `rich_nlas` feature flag for this, but since it existed before, this might still be a breaking change for some users. Could alternatively introduce another feature flag specifically for this change. 
- Once this is accepted, I would also like to add corresponding functionality in the `rtnetlink` crate.

### CODE REVIEW

**Comment by jreppnow** [comment]
The captured data in the test case is from: 

```sh
sudo strace -s 1000 -f -e trace=network ip link add link enp5s0 name eth0.75 type vlan id 75 egress 3:4 ingress 0:1 1:2
```

I had to adjust the length field for `IFLA_INFO_KIND` and add the padding manually, as iproute2 does not use null-terminated strings (aka c strings) for this specific field.

**Comment by cathay4t** [comment]
@jreppnow Thanks for the patch! Please rebase to latest commit.

I personally dislike the idea of `rich_nlas` feature and plan to remove it in next release 0.17.0. Hence please remove the use of `rich_nlas` from your code. Thanks!

I guess this VLAN QoS support also require effort on `rtnetlink` crate, can you provide a PR to `rtnetlink` with example code approving the code here is actual working.

Thank you!

**Comment by jreppnow** [comment]
Hi @cathay4t, 

1. I have made the requested changes here (rebase and removal of `rich_nlas` feature). 
2. Made a (preliminary) PR (https://github.com/rust-netlink/rtnetlink/pull/24) to `rtnetlink` making use of the changes here. See the notes there for more details.

**Review by cathay4t — DISMISSED** [review]
Looks great to me.

Please change the commit message title since we are not using `rick_nlas` anymore in this patch.

After that, we are good to go.

**Comment by cathay4t** [comment]
My bad the commit title is good enough. Merging.

**Review by cathay4t — APPROVED** [review]

**Pull request merged**
