### PR TITLE
Rename NetnsId to avoid surprises

### PR DESCRIPTION
**Pull request by Gilnaa**
Hey :)
This is a breaking change; wasn’t sure if it is okay for a <1.0 version, but thought it’s better to try with a patch then opening an issue.

Was also wondering if it’s proper to add doc-comments for these enum variants. If that’s the case I might open a followup PR

---

There are 4 IFLA_* values related to network-namespaces. The following 3 control the `dest_net` of the link:
 - `IFLA_NET_NS_PID`      by PID
 - `IFLA_NET_NS_FD`       by FD
 - `IFLA_TARGET_NETNSID`  by ID    (an alias for `IFLA_IF_NETNSID`)

And the last one controls the `link_net` of the link:
 - `IFLA_LINK_NETNSID`    by ID

Currently netlink-packet-route provides 3 enum variants with similar names, which suggest they do the same thing with different input
 - `NetNsFd`    => Corresponds to IFLA_NET_NS_FD
 - `NetNsPid`   => Corresponds to IFLA_NET_NS_PID
 - `NetnsId`    => Corresponds to IFLA_LINK_NETNSID, not IFLA_TARGET_NETNSID

The similar naming might cause confusion, since it matches neither the meaning nor the underlying CONSTANT_NAME used by the kernel.

### CODE REVIEW

**Review by little-dude — APPROVED** [review]
Nice catch, and thanks for the detailed explanation.

**Comment by Gilnaa** [comment]
@little-dude

WRT clippy:
Couldn't reproduce this locally, but I assume it complains about `TryFrom` being imported even though it is part of the prelude.
Would like a fix to this in a separate PR or is it easier to bundle it in this one?

WRT coverage:
Seems like a false-positive to say that the coverage was degraded, given that a single untested identifier was changed;
but I guess it wouldn't hurt to add it to one of the serialization tests.
I'll try finding some time in the coming days

**Comment by little-dude** [comment]
I've opened an Mr for clippy already. But I don't date merging MRs, since I've been inactive on the project for 2+ years :D

**Review by cathay4t — APPROVED** [review]
LGTM. I will be carefull on matching kernel constant name to rust enum entry name.

**Comment by Gilnaa** [comment]
Thank you! :)

**Pull request merged**
